version: '3'
services:
  # PostgreSQL Database
  db:
    image: postgres:latest
    container_name: postgres_test
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=coding_tester
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=Asia/Seoul
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    command: postgres -c shared_buffers=128MB -c max_connections=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/postgres-data 