name: Docker Compose CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and deploy with Docker Compose
        run: |
          docker compose build
          docker compose up -d

      - name: Verify deployment
        run: |
          docker compose ps
          echo "Waiting for services to start..."
          sleep 20
          # 컨테이너 상태 확인
          docker ps
          # 서비스 상태 확인을 위한 curl 명령 (필요시 수정)
          curl -s --retry 5 --retry-delay 5 --retry-max-time 30 http://localhost:4211 > /dev/null || echo "서비스 접속 실패했지만 배포는 완료됨"
          
      - name: Clean up
        if: always()
        run: |
          echo "Cleaning up resources..."
          # 로그 캡처 (선택사항)
          docker compose logs > deployment-logs.txt 
